"use client";
import "./styles/GlobalStyle.scss";
import styled from "styled-components";
import Header from "@/components/Header/header";
import StyledComponentsRegistry from "@/lib/registry";

import { theme } from "./theme";
import { ThemeProvider } from "styled-components";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Inter, Life_Savers, Capriola } from "next/font/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

export const life_savers = Life_Savers({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
  style: ["normal"],
  display: "swap",
});

export const capriola = Capriola({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "K-Components",
  description:
    "This is Component & Animation Collections, Generated by Kim Hyeon su",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(process.env.NEXT_PUBLIC_HELLO);
  const client = new QueryClient();
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Leckerli+One"
          rel="stylesheet"
        ></link>
      </head>
      <body className={`${inter.className} body`}>
        <QueryClientProvider client={client}>
          {process.env.NODE_ENV === "development" && <ReactQueryDevtools />}
          <StyledComponentsRegistry>
            <ThemeProvider theme={theme}>
              <Applayout>
                <header>
                  <Header />
                </header>
                <Main>{children}</Main>
              </Applayout>
            </ThemeProvider>
          </StyledComponentsRegistry>
        </QueryClientProvider>
      </body>
    </html>
  );
}

const Applayout = styled.div`
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  width: 100vw;
  overflow-x: hidden;
  flex: 1;
`;

const Main = styled.main`
  background-color: ${(props) => props.theme.major.gray.light};
  padding-top: 100px;
  margin: auto;
`;
