import StyledComponentsRegistry from "@/lib/registry";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools/build/lib/devtools";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "K-Components",
  description:
    "This is Component & Animation Collections, Generated by Kim Hyeon su",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const client = new QueryClient();
  return (
    <html lang="en">
      <QueryClientProvider client={client}>
        <ReactQueryDevtools />
        <StyledComponentsRegistry>
          <body className={inter.className}>{children}</body>
        </StyledComponentsRegistry>
      </QueryClientProvider>
    </html>
  );
}
